# Generated by Django 4.2.25 on 2025-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_businesselement_accessrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='can_create_for_other_users',
            field=models.BooleanField(default=False),
        ),
    ]
